### ISSUE TITLE
skin color doesn't appear to change when race changes

### ISSUE THREAD

**Issue by wassname** [makehuman-js/makehuman-js-example#1]

**Comment by Colorfingers** [comment]
Three.color takes RGB values... how did you come by the following values?  They look like specular color values.

this.human.mesh.material.materials[0].color = new THREE.Color(0.6451834425332652, 0.541358126188251, 0.46583313890034395)

**Comment by wassname** [comment]
I think I just used online colour wheels and experimented to find something that looks OK, but it does vary by screen. If you find a better skin-like colour let me know and I'll replace it.

**Comment by Colorfingers** [comment]
No, it's fine... it just looked odd to me.  I see that there are different options for entering colors so this must be just another method I am not aware of.
