### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by omkarap55** [makehuman-js/makehuman-js-example#4]
Hi, I have cloned the repo & when I run npm install in cloned directory, I get following error:

npm ERR! Failed at the node-sass@3.13.1 postinstall script.

Steps to reproduce issue:

- Clone the Repo
- npm install

**Comment by wassname** [comment]
Great to see your giving it a try.

Can you post the full failure message, please? As well as other details I may need in order to replicate it, e.g. your system, node version, and more. 

Feel free to try a different version of node-sass, I don't think the exact version is very important.

**Comment by omkarap55** [comment]
Hi, I tried different version of node-sass & its working fine. Thanks a lot!
