### ISSUE TITLE
arrangening all scattered repositories

### ISSUE THREAD

**Issue by Nilam-tule** [makehuman-js/makehuman-js-example#7]
Can u please tell what tree structure my program should follow . and please tell about how to run this if any video on youtube refer that to me. As I am no able to run this through your readme file

**Comment by wassname** [comment]
This is a draft stage project. Right now it's suitable for experts who want to help improve the documentation. If you are able and willing to help improve the repo then please do.

At the moment very few people use this and certainly no one pays for it. So I'm not going to take the time to rewrite the documentation.
