### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by blake-bori** [makehuman-js/makehuman-js-example#8]
How are you?
I am a student working on a new project using this project in Korea.

It's not easy to understand this good open source because I lack a lot of things.
I want to use this source code to work on a new project, but I'm having a hard time even testing this code.

Fortunately, I tried to run this repository after cleaning it, but it's very difficult for me to find the part that needs to be corrected.
I'd like to know in detail how to modify this code.

I look forward to your response. Thank you.

**Comment by sswon314** [comment]
> _No description provided._
